
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Symu {
  /* terminals */
  public static final int tHeigth = 29;
  public static final int tBorder = 32;
  public static final int tDoble = 17;
  public static final int tPuntoComa = 7;
  public static final int tColor = 31;
  public static final int tSuma = 19;
  public static final int tY = 28;
  public static final int tNumero = 35;
  public static final int tX = 27;
  public static final int tDiv = 22;
  public static final int tCaracter = 15;
  public static final int tMayorQ = 24;
  public static final int tTrue = 12;
  public static final int tComa = 18;
  public static final int tEntero = 16;
  public static final int tComponent = 3;
  public static final int tFalse = 13;
  public static final int tLlaveC = 8;
  public static final int tLlaveA = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int tWidth = 30;
  public static final int tMenorQ = 25;
  public static final int tResta = 20;
  public static final int tId = 14;
  public static final int tReturn = 4;
  public static final int tCadena = 2;
  public static final int tVar = 5;
  public static final int tIgual = 6;
  public static final int tMult = 21;
  public static final int tPow = 23;
  public static final int tIdEtq = 34;
  public static final int tDiagonal = 33;
  public static final int tPanel = 26;
  public static final int tParC = 11;
  public static final int tParA = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tCadena",
  "tComponent",
  "tReturn",
  "tVar",
  "tIgual",
  "tPuntoComa",
  "tLlaveC",
  "tLlaveA",
  "tParA",
  "tParC",
  "tTrue",
  "tFalse",
  "tId",
  "tCaracter",
  "tEntero",
  "tDoble",
  "tComa",
  "tSuma",
  "tResta",
  "tMult",
  "tDiv",
  "tPow",
  "tMayorQ",
  "tMenorQ",
  "tPanel",
  "tX",
  "tY",
  "tHeigth",
  "tWidth",
  "tColor",
  "tBorder",
  "tDiagonal",
  "tIdEtq",
  "tNumero"
  };
}

